import type { Metadata } from "next";
import "./globals.css";
import Header from "@/modules/Header/Header";
import Footer from "@/modules/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-dark min-h-[100svh] flex flex-col">
        <Header />
        <div className="flex flex-col flex-1">
          <main className="bg-background-gray flex-1 w-full overflow-y-auto overflow-x-hidden">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
